version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./nodejs/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: ./nodejs
    restart: unless-stopped
    env_file: ./nodejs/.env
    ports:
      - 5000:5000
    environment:
      - POSTGRES_HOST=postgresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    stdin_open: true
    tty: true

volumes: 
  db: